- name: Update cluster configuration
  hosts: all
  roles:
    - role: k3s
    - role: common

  tasks:
    - name: Only on physical tmms
      import_role:
        name: tmm
      when: "'tmm' in group_names"
