---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
  namespace: storage
spec:
  interval: 24h
  url: https://openebs.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
spec:
  chart:
    spec:
      chart: openebs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 24h
  values:
    # ref: https://github.com/openebs/lvm-localpv/blob/develop/deploy/helm/charts/values.yaml
    lvm-localpv:
      enabled: true

    crd:
      volumeSnapshot: false

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvm
parameters:
  # ref: https://github.com/openebs/lvm-localpv/blob/develop/docs/storageclasses.md
  storage: "lvm"
  volgroup: "kube"
  fsType: btrfs  # ext4 is supported too, among others
allowVolumeExpansion: true
provisioner: local.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
