---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
spec:
  chart:
    spec:
      chart: openebs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 24h
  values:
    # NOTE: I might want to change to this top-level chart so I can get ndm and other related openebs
    # stuff: https://github.com/openebs/charts/tree/main/charts/openebs

    # ref: https://github.com/openebs/lvm-localpv/blob/develop/deploy/helm/charts/values.yaml
    lvm-localpv:
      enabled: true

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvm
parameters:
  # ref: https://github.com/openebs/lvm-localpv/blob/develop/docs/storageclasses.md
  storage: "lvm"
  volgroup: "kube"
  fsType: btrfs  # ext4 is supported too, among others
allowVolumeExpansion: true
provisioner: local.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
