---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smb-csi
  namespace: storage
spec:
  chart:
    spec:
      chart: csi-driver-smb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: smb-csi
  interval: 24h
  values:
    # ref: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/charts/v1.10.0/csi-driver-smb/values.yaml
