#!/usr/bin/env bash

set -euo pipefail

# Should be cluster name like `tmm` or `alpha`
CLUSTER_NAME=${1}

if [[ ${CLUSTER_NAME} != 'tmm' ]] ; then
    echo "Unsupported cluster!" >&2
    exit 1
fi

# NOTE: this json file is supposed to be base64-encoded before putting it into kubernetes (and the
# kubernetes secret will base64 encode it again).  Strange but true.
kubectl create secret generic opcreds \
    -n secrets \
    --from-literal=json="$(op read op://homelab/${CLUSTER_NAME}-1password-connect/1password-credentials.json | base64)"

kubectl create secret generic connect \
    -n secrets \
    --from-literal=token="$(op read op://homelab/${CLUSTER_NAME}-1password-connect/token)"

