#!/usr/bin/env bash

set -euo pipefail

# Should be cluster name like `tmm` or `alpha`
CLUSTER_NAME=${1}

if [[ ${CLUSTER_NAME} != 'tmm' ]] ; then
    echo "Unsupported cluster!" >&2
    exit 1
fi

kubectl create secret generic opcreds \
    -n secrets \
    --from-literal=json="$(op read op://homelab/${CLUSTER_NAME}-1password-connect/1password-credentials.json)"

kubectl create secret generic connect \
    -n secrets \
    --from-literal=token="$(op read op://homelab/${CLUSTER_NAME}-1password-connect/token)"

