#!/usr/bin/env bash

set -euo pipefail

# Should be cluster name like `tmm` or `alpha`
CLUSTER_NAME=${1}

if [[ ${CLUSTER_NAME} != 'tmm' ]] ; then
    echo "Unsupported cluster!" >&2
    exit 1
done

op run \
    kubectl create secret generic op-credentials \
        -n secrets \
        --from-literal=op-session="$(op read op://homelab/${CLUSTER_NAME}-1password-connect/1password-credentials.json)"

op run \
    kubectl create secret generic onepassword-token \
        -n secrets \
        --from-literal=token="$(op read op://homelab/${CLUSTER_NAME}-1password-connect/token)"

