- name: install packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - nfs-common
      - open-iscsi
        #- aptitude
        #- git
        #- htop
        #- iotop
        #- jq
        #- tmux
        #- zsh
        #- smartmontools

- name: "systemd-networkd: Don't interefere networks that aren't yours"
  become: true
  community.general.ini_file:
    path: /etc/systemd/networkd.conf
    section: Network
    option: "{{ item }}"
    value: "no"
  loop:
    - ManageForeignRoutingPolicyRules
    - ManageForeignRoutes

- name: "systemd: Disable unnecessary services."
  become: true
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: "{{ item }}"
  loop:
    - snapd

