apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: network
spec:
  interval: 12h0s
  url: https://kubernetes-sigs.github.io/external-dns/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
  interval: 10m0s
  # ref: https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
  values:
    policy: sync
    txtPrefix: externaldns-
    txtOwnerId: homelab
    provider: aws
    env:
      - name: AWS_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-certbot
            key: access_key
      - name: AWS_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: aws-certbot
            key: secret_key




