#!/usr/bin/env bash

set -euo pipefail

helm upgrade --install \
    --repo https://1password.github.io/connect-helm-charts \
    connect connect \
    --namespace secrets \
    --values 1password-connect.values.yaml
