---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: connect
  namespace: secrets
spec:
  chart:
    spec:
      chart: connect
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: onepassword
  interval: 24h
  values:
    # ref: https://github.com/1Password/connect-helm-charts/tree/main/charts/connect
    operator:
      create: true

      # Operator will restart pods when secret changes (on poll that discovers update)
      autoRestart: true

      pollingInterval: 600

      token:
        # This secret configured by bless-1password script
        name: connect
        key: token



    connect:
      create: true

      # This secret is set up by the bless-1password script
      credentialsName: opcreds
      credentialsKey: json

      serviceType: ClusterIP


