#!/usr/bin/env bash

# NOTE: I'm not strictly sure this is necessary.  As I understood things, patroni would set passwords for
# me when formed properly in the timescale-credentials secret and that's why this script works based on
# that same secret (from the 1Password side).
#
# If Patroni doesn't do this in a way that works out for me, I can surely work something like this script
# into the process of database bring up.

set -euo pipefail

USERS=(ha michael)

for u in "${USERS[@]}" ; do
    echo "Setting password for user ${u}"

    # The password _to set_ on this specific user
    USERPASS=$(op read "op://homelab-tmm/timescale-credentials/PATRONI_${u}_PASSWORD")

    echo "ALTER USER ${u} WITH PASSWORD '${USERPASS}'" \
        | PGPASSWORD=$(op read 'op://homelab-tmm/timescale-credentials/PATRONI_SUPERUSER_PASSWORD') \
            psql \
                -h tmm0.odell.sh \
                -U postgres \
                -d postgres \
                --file=-

done
