apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ha
  namespace: ha
spec:
  interval: 5m0s
  url: https://github.com/michael-odell/home-assistant
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include chart directory
    !/helm/
