---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ha
  labels:
    app.kubernetes.io/instance: ha
    app.kubernetes.io/name: ha
    app.kubernetes.io/version: 2023.5.4
  name: ha
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: ha
      app.kubernetes.io/name: ha
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: ha
      labels:
        app.kubernetes.io/instance: ha
        app.kubernetes.io/name: ha
    spec:
      automountServiceAccountToken: false
      hostNetwork: true
      containers:
      - env:
        - name: TZ
          value: America/Denver
        image: ghcr.io/home-assistant/home-assistant:2023.5.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        name: ha
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        - containerPort: 5353
          name: homekit-tcp
          protocol: TCP
        - containerPort: 21064
          name: homekit-bridge
          protocol: UDP
        - containerPort: 21065
          name: homekit-tv
          protocol: UDP

        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1

        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 8123
          timeoutSeconds: 1

        volumeMounts:
        - mountPath: /config
          name: config

      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      serviceAccountName: default

      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: ha-config
