apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ha
  namespace: ha
spec:
  interval: 5m
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values: {}

