apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ha
  namespace: ha
spec:
  interval: 5m
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: ha
        namespace: ha
      interval: 1m
  values: {}

