apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: ha
  namespace: ha
spec:
  interval: 5m0s
  chart: home-assistant
  # TODO change to ChartVersion when/if I start incrementing that
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: ha
