---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ha
  name: ha-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: smb
