apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: connect
  namespace: secrets
spec:
  chart:
    spec:
      chart: connect
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: onepassword
  interval: 24h
  values:
    operator:
      create: true
      autoRestart: true
      pollingInterval: 600
      token:
        name: connect
        key: token
    connect:
      create: true
      credentialsName: opcreds
      credentialsKey: json
      serviceType: ClusterIP
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: connect
  namespace: flux-system
spec:
  interval: 12h
  url: https://1password.github.io/connect-helm-charts
